### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by den-run-ai** [sn6uv/rmathics#1]
what is the license? GPL, BSD, MIT?

**Comment by sn6uv** [comment]
I've decided to release this under the (original) BSD license. If you'd prefer something else let me know and we can discuss it.

**Comment by den-run-ai** [comment]
so looks like now mathics could be integrated with sympy?

**Comment by sn6uv** [comment]
Hi denfromufa,

Actually, Mathics uses Sympy to do much of it's symbolic manipulations
although certainly they could be more integrated.

Cheers,
Angus

**Comment by sn6uv** [comment]
BTW: This isn't the main Mathics project. That one is found at: https:// github.com/ mathics/Mathics

This project is just an experiment with RPython.

**Comment by den-run-ai** [comment]
main branch is GPL, that is why only mathics is using sympy (one-way usage
only)

**Comment by sn6uv** [comment]
I see. I know a while back SymPy were looking into implementing a more robust Mathematica parser. At the time the SymPy pattern matching was too primitive. They could perhaps adapt this library to that purpose. Alternatively, I'm happy to relicense the actual Mathics parser under BSD or equivalent.
